#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrnekSite.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OrnekSiteDB")]
	public partial class VerilerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertResim(Resim instance);
    partial void UpdateResim(Resim instance);
    partial void DeleteResim(Resim instance);
    partial void InsertSabitBilgi(SabitBilgi instance);
    partial void UpdateSabitBilgi(SabitBilgi instance);
    partial void DeleteSabitBilgi(SabitBilgi instance);
    partial void InsertYazi(Yazi instance);
    partial void UpdateYazi(Yazi instance);
    partial void DeleteYazi(Yazi instance);
    partial void InsertYorum(Yorum instance);
    partial void UpdateYorum(Yorum instance);
    partial void DeleteYorum(Yorum instance);
    #endregion
		
		public VerilerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OrnekSiteDBConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VerilerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VerilerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VerilerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VerilerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Resim> Resims
		{
			get
			{
				return this.GetTable<Resim>();
			}
		}
		
		public System.Data.Linq.Table<SabitBilgi> SabitBilgis
		{
			get
			{
				return this.GetTable<SabitBilgi>();
			}
		}
		
		public System.Data.Linq.Table<Yazi> Yazis
		{
			get
			{
				return this.GetTable<Yazi>();
			}
		}
		
		public System.Data.Linq.Table<Yorum> Yorums
		{
			get
			{
				return this.GetTable<Yorum>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Resim")]
	public partial class Resim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _URL;
		
		private System.Nullable<System.DateTime> _EklemeTarihi;
		
		private string _Aciklama;
		
		private bool _AktifMi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnEklemeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnEklemeTarihiChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnAktifMiChanging(bool value);
    partial void OnAktifMiChanged();
    #endregion
		
		public Resim()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EklemeTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> EklemeTarihi
		{
			get
			{
				return this._EklemeTarihi;
			}
			set
			{
				if ((this._EklemeTarihi != value))
				{
					this.OnEklemeTarihiChanging(value);
					this.SendPropertyChanging();
					this._EklemeTarihi = value;
					this.SendPropertyChanged("EklemeTarihi");
					this.OnEklemeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AktifMi", DbType="Bit NOT NULL")]
		public bool AktifMi
		{
			get
			{
				return this._AktifMi;
			}
			set
			{
				if ((this._AktifMi != value))
				{
					this.OnAktifMiChanging(value);
					this.SendPropertyChanging();
					this._AktifMi = value;
					this.SendPropertyChanged("AktifMi");
					this.OnAktifMiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SabitBilgi")]
	public partial class SabitBilgi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Kod;
		
		private string _Isim;
		
		private string _Deger;
		
		private bool _AktifMi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKodChanging(string value);
    partial void OnKodChanged();
    partial void OnIsimChanging(string value);
    partial void OnIsimChanged();
    partial void OnDegerChanging(string value);
    partial void OnDegerChanged();
    partial void OnAktifMiChanging(bool value);
    partial void OnAktifMiChanged();
    #endregion
		
		public SabitBilgi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this.OnKodChanging(value);
					this.SendPropertyChanging();
					this._Kod = value;
					this.SendPropertyChanged("Kod");
					this.OnKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isim", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Isim
		{
			get
			{
				return this._Isim;
			}
			set
			{
				if ((this._Isim != value))
				{
					this.OnIsimChanging(value);
					this.SendPropertyChanging();
					this._Isim = value;
					this.SendPropertyChanged("Isim");
					this.OnIsimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deger", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Deger
		{
			get
			{
				return this._Deger;
			}
			set
			{
				if ((this._Deger != value))
				{
					this.OnDegerChanging(value);
					this.SendPropertyChanging();
					this._Deger = value;
					this.SendPropertyChanged("Deger");
					this.OnDegerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AktifMi", DbType="Bit NOT NULL")]
		public bool AktifMi
		{
			get
			{
				return this._AktifMi;
			}
			set
			{
				if ((this._AktifMi != value))
				{
					this.OnAktifMiChanging(value);
					this.SendPropertyChanging();
					this._AktifMi = value;
					this.SendPropertyChanged("AktifMi");
					this.OnAktifMiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Yazi")]
	public partial class Yazi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Baslik;
		
		private string _Metin;
		
		private bool _AktifMi;
		
		private System.Nullable<System.DateTime> _EklemeTarihi;
		
		private EntitySet<Yorum> _Yorums;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBaslikChanging(string value);
    partial void OnBaslikChanged();
    partial void OnMetinChanging(string value);
    partial void OnMetinChanged();
    partial void OnAktifMiChanging(bool value);
    partial void OnAktifMiChanged();
    partial void OnEklemeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnEklemeTarihiChanged();
    #endregion
		
		public Yazi()
		{
			this._Yorums = new EntitySet<Yorum>(new Action<Yorum>(this.attach_Yorums), new Action<Yorum>(this.detach_Yorums));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Baslik", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Baslik
		{
			get
			{
				return this._Baslik;
			}
			set
			{
				if ((this._Baslik != value))
				{
					this.OnBaslikChanging(value);
					this.SendPropertyChanging();
					this._Baslik = value;
					this.SendPropertyChanged("Baslik");
					this.OnBaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Metin", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Metin
		{
			get
			{
				return this._Metin;
			}
			set
			{
				if ((this._Metin != value))
				{
					this.OnMetinChanging(value);
					this.SendPropertyChanging();
					this._Metin = value;
					this.SendPropertyChanged("Metin");
					this.OnMetinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AktifMi", DbType="Bit NOT NULL")]
		public bool AktifMi
		{
			get
			{
				return this._AktifMi;
			}
			set
			{
				if ((this._AktifMi != value))
				{
					this.OnAktifMiChanging(value);
					this.SendPropertyChanging();
					this._AktifMi = value;
					this.SendPropertyChanged("AktifMi");
					this.OnAktifMiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EklemeTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> EklemeTarihi
		{
			get
			{
				return this._EklemeTarihi;
			}
			set
			{
				if ((this._EklemeTarihi != value))
				{
					this.OnEklemeTarihiChanging(value);
					this.SendPropertyChanging();
					this._EklemeTarihi = value;
					this.SendPropertyChanged("EklemeTarihi");
					this.OnEklemeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Yazi_Yorum", Storage="_Yorums", ThisKey="ID", OtherKey="YaziID")]
		public EntitySet<Yorum> Yorums
		{
			get
			{
				return this._Yorums;
			}
			set
			{
				this._Yorums.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Yorums(Yorum entity)
		{
			this.SendPropertyChanging();
			entity.Yazi = this;
		}
		
		private void detach_Yorums(Yorum entity)
		{
			this.SendPropertyChanging();
			entity.Yazi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Yorum")]
	public partial class Yorum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Metin;
		
		private string _Mail;
		
		private System.DateTime _EklemeTarihi;
		
		private bool _AktifMi;
		
		private int _YaziID;
		
		private EntityRef<Yazi> _Yazi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMetinChanging(string value);
    partial void OnMetinChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnEklemeTarihiChanging(System.DateTime value);
    partial void OnEklemeTarihiChanged();
    partial void OnAktifMiChanging(bool value);
    partial void OnAktifMiChanged();
    partial void OnYaziIDChanging(int value);
    partial void OnYaziIDChanged();
    #endregion
		
		public Yorum()
		{
			this._Yazi = default(EntityRef<Yazi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Metin", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Metin
		{
			get
			{
				return this._Metin;
			}
			set
			{
				if ((this._Metin != value))
				{
					this.OnMetinChanging(value);
					this.SendPropertyChanging();
					this._Metin = value;
					this.SendPropertyChanged("Metin");
					this.OnMetinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EklemeTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime EklemeTarihi
		{
			get
			{
				return this._EklemeTarihi;
			}
			set
			{
				if ((this._EklemeTarihi != value))
				{
					this.OnEklemeTarihiChanging(value);
					this.SendPropertyChanging();
					this._EklemeTarihi = value;
					this.SendPropertyChanged("EklemeTarihi");
					this.OnEklemeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AktifMi", DbType="Bit NOT NULL")]
		public bool AktifMi
		{
			get
			{
				return this._AktifMi;
			}
			set
			{
				if ((this._AktifMi != value))
				{
					this.OnAktifMiChanging(value);
					this.SendPropertyChanging();
					this._AktifMi = value;
					this.SendPropertyChanged("AktifMi");
					this.OnAktifMiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YaziID", DbType="Int NOT NULL")]
		public int YaziID
		{
			get
			{
				return this._YaziID;
			}
			set
			{
				if ((this._YaziID != value))
				{
					if (this._Yazi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnYaziIDChanging(value);
					this.SendPropertyChanging();
					this._YaziID = value;
					this.SendPropertyChanged("YaziID");
					this.OnYaziIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Yazi_Yorum", Storage="_Yazi", ThisKey="YaziID", OtherKey="ID", IsForeignKey=true)]
		public Yazi Yazi
		{
			get
			{
				return this._Yazi.Entity;
			}
			set
			{
				Yazi previousValue = this._Yazi.Entity;
				if (((previousValue != value) 
							|| (this._Yazi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Yazi.Entity = null;
						previousValue.Yorums.Remove(this);
					}
					this._Yazi.Entity = value;
					if ((value != null))
					{
						value.Yorums.Add(this);
						this._YaziID = value.ID;
					}
					else
					{
						this._YaziID = default(int);
					}
					this.SendPropertyChanged("Yazi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
